### ISSUE TITLE
Not working under windows

### ISSUE THREAD

**Issue by heckad** [asottile/flake8-walrus#6]
Output
```
Check for added large files..............................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check Yaml...............................................................Passed
Debug Statements (Python)................................................Passed
Fix python encoding pragma...............................................Passed
pyupgrade................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

flake8.plugins.manager    MainProcess     55 INFO     Loading entry-points for "flake8.extension".
flake8.plugins.manager    MainProcess     63 INFO     Loading entry-points for "flake8.report".
flake8.plugins.manager    MainProcess     69 INFO     Loading plugin "F" from entry-point.
flake8.plugins.manager    MainProcess    114 INFO     Loading plugin "pycodestyle.ambiguous_identifier" from entry-point.
flake8.plugins.manager    MainProcess    118 INFO     Loading plugin "pycodestyle.bare_except" from entry-point.
flake8.plugins.manager    MainProcess    118 INFO     Loading plugin "pycodestyle.blank_lines" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.break_after_binary_operator" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.break_before_binary_operator" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.comparison_negative" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.comparison_to_singleton" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.comparison_type" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.compound_statements" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.continued_indentation" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.explicit_line_join" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.extraneous_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.imports_on_separate_lines" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.indentation" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.maximum_doc_length" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.maximum_line_length" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.missing_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.missing_whitespace_after_import_keyword" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.missing_whitespace_around_operator" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.module_imports_on_top_of_file" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.python_3000_async_await_keywords" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.python_3000_backticks" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.python_3000_has_key" from entry-point.
flake8.plugins.manager    MainProcess    119 INFO     Loading plugin "pycodestyle.python_3000_invalid_escape_sequence" from entry-point.
flake8.plugins.manager    MainProcess    120 INFO     Loading plugin "pycodestyle.python_3000_not_equal" from entry-point.
flake8.plugins.manager    MainProcess    120 INFO     Loading plugin "pycodestyle.python_3000_raise_comma" from entry-point.
flake8.plugins.manager    MainProcess    120 INFO     Loading plugin "pycodestyle.tabs_obsolete" from entry-point.
flake8.plugins.manager    MainProcess    120 INFO     Loading plugin "pycodestyle.tabs_or_spaces" from entry-point.
flake8.plugins.manager    MainProcess    120 INFO     Loading plugin "pycodestyle.trailing_blank_lines" from entry-point.
flake8.plugins.manager    MainProcess    120 INFO     Loading plugin "pycodestyle.trailing_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    120 INFO     Loading plugin "pycodestyle.whitespace_around_comma" from entry-point.
flake8.plugins.manager    MainProcess    120 INFO     Loading plugin "pycodestyle.whitespace_around_keywords" from entry-point.
flake8.plugins.manager    MainProcess    120 INFO     Loading plugin "pycodestyle.whitespace_around_named_parameter_equals" from entry-point.
flake8.plugins.manager    MainProcess    120 INFO     Loading plugin "pycodestyle.whitespace_around_operator" from entry-point.
flake8.plugins.manager    MainProcess    120 INFO     Loading plugin "pycodestyle.whitespace_before_comment" from entry-point.
flake8.plugins.manager    MainProcess    120 INFO     Loading plugin "pycodestyle.whitespace_before_parameters" from entry-point.
flake8.plugins.manager    MainProcess    120 INFO     Loading plugin "ASN" from entry-point.
flake8.plugins.manager    MainProcess    143 INFO     Loading plugin "C90" from entry-point.
flake8.plugins.manager    MainProcess    144 INFO     Loading plugin "default" from entry-point.
flake8.plugins.manager    MainProcess    146 INFO     Loading plugin "pylint" from entry-point.
flake8.plugins.manager    MainProcess    146 INFO     Loading plugin "quiet-filename" from entry-point.
flake8.plugins.manager    MainProcess    146 INFO     Loading plugin "quiet-nothing" from entry-point.
flake8.checker            MainProcess    147 WARNING  The --jobs option is not available on Windows due to a bug (https://bugs.python.org/issue27649) in Python 2.7.11+ and 3.3+. We have detected that you are running an unsupported version of Python on Windows. Igno
ring --jobs arguments.
flake8.checker            MainProcess    148 INFO     Making checkers
flake8.checker            MainProcess    161 INFO     Checking 40 files
flake8.checker            MainProcess    413 CRITICAL Plugin F raised an unexpected exception
Traceback (most recent call last):
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\flake8\checker.py", line 435, in run_check
    return plugin["plugin"](**arguments)
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\flake8\plugins\pyflakes.py", line 90, in __init__
    super(FlakesChecker, self).__init__(
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 673, in __init__
    self.runDeferred(self._deferredFunctions)
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 710, in runDeferred
    handler()
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 1474, in runFunction
    self.handleChildren(node, omit='decorator_list')
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 1120, in handleNode
    handler(node)
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 1120, in handleNode
    handler(node)
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 1120, in handleNode
    handler(node)
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 1120, in handleNode
    handler(node)
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 1073, in handleChildren
    self.handleNode(node, tree)
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 1119, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "c:\users\asus\.cache\pre-commit\repou4_z9jh9\py_env-python3.8\lib\site-packages\pyflakes\checker.py", line 909, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'FlakesChecker' object has no attribute 'NAMEDEXPR'
flake8.main.application   MainProcess    430 INFO     Finished running
flake8.main.application   MainProcess    430 INFO     Reporting errors
flake8.main.application   MainProcess    431 INFO     Found a total of 15 violations and reported 4
"pyflakes" failed during execution due to "'FlakesChecker' object has no attribute 'NAMEDEXPR'"
Run flake8 with greater verbosity to see more details
integrations_with_exchanges/models/base.py:152:31: E203 whitespace before ':'
integrations_with_exchanges/models/base.py:152:32: E231 missing whitespace after ':'
integrations_with_exchanges/models/base.py:246:27: E203 whitespace before ':'
integrations_with_exchanges/models/base.py:246:28: E231 missing whitespace after ':'

mypy.....................................................................Passed
```

.pre-commit-config.yml
```
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        additional_dependencies: [flake8-walrus]
```

**Comment by asottile** [comment]
that's a crash in pyflakes, not in my plugin -- you're looking for https://github.com/PyCQA/pyflakes/pull/457
